[build]
  publish = "dist"
  command = "npm run build"

# Basit yönlendirme - direkt ana sayfaya
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# SPA routing for language subdirectories
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200

[[redirects]]
  from = "/tr/*"
  to = "/tr/index.html"
  status = 200

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/it/*"
  to = "/it/index.html"
  status = 200

[[redirects]]
  from = "/pt/*"
  to = "/pt/index.html"
  status = 200

[[redirects]]
  from = "/ru/*"
  to = "/ru/index.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/index.html"
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/index.html"
  status = 200

[[redirects]]
  from = "/ko/*"
  to = "/ko/index.html"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200

[[redirects]]
  from = "/hi/*"
  to = "/hi/index.html"
  status = 200

[[redirects]]
  from = "/id/*"
  to = "/id/index.html"
  status = 200

[[redirects]]
  from = "/vi/*"
  to = "/vi/index.html"
  status = 200

[[redirects]]
  from = "/th/*"
  to = "/th/index.html"
  status = 200

[[redirects]]
  from = "/pl/*"
  to = "/pl/index.html"
  status = 200

[[redirects]]
  from = "/nb/*"
  to = "/nb/index.html"
  status = 200

[[redirects]]
  from = "/sv/*"
  to = "/sv/index.html"
  status = 200

[[redirects]]
  from = "/fi/*"
  to = "/fi/index.html"
  status = 200

[[redirects]]
  from = "/fa/*"
  to = "/fa/index.html"
  status = 200

[[redirects]]
  from = "/tl/*"
  to = "/tl/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"