name = "bestvpn-geo-router"
main = "_worker.js"
compatibility_date = "2024-01-15"

# Route configuration
[[routes]]
pattern = "bestvpn.digital/*"
zone_name = "bestvpn.digital"

# Environment variables (if needed)
[vars]
SITE_URL = "https://bestvpn.digital"

# Build configuration
[build]
command = ""

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
